### ISSUE TITLE
Länk mellan Libris och LibrisXL?

### ISSUE THREAD

**Issue by dpriskorn** [libris/librisxl#1006]
Jag skulle vilja kunna gå från https://www.wikidata.org/wiki/Q44272 -> https://libris.kb.se/katalogisering/wt799chf1cm1w3z -> https://libris.kb.se/hitlist?d=libris&q=f%c3%b6rf%3a(Michel+Foucault)&f=ext&spell=true&hist=true&p=1 men det verkar inte gå?

Förstår gamla interfacet sig inte på Libris-URI? Varför inte? Har ni inte matchat så jag slipper text-strängar där med?

**Comment by salgo60** [comment]
Såg att ni länkar Wikidata 

FYI så **mergar Wikidata** då och då så om ni vill ha senaste Qnummer bör man uppdatera LIBRISXL

* [SPARQL som hittar 30 stycken](https://w.wiki/4DdR) som mergats de senaste 8 dagarna
  * **tgtQid** är nya id:et
  * video hur [man hämtar detta som kod](https://youtu.be/-1weqOjM1Ec)
  * bra video hur en annan person integrerar med Wikidata och kollar merge se https://github.com/salgo60/spa2Commons/issues/3#issuecomment-932092733
 
![image](https://user-images.githubusercontent.com/14206509/137402667-7e949b9c-93e9-4465-8244-b6fb8733df49.png)

**Comment by salgo60** [comment]
Här har ni > 11000 LIBRISXL ämnesord kopplade till Wiklidata [på en karta](https://w.wiki/iVh) / som [en lista ](https://w.wiki/4DdW)

![image](https://user-images.githubusercontent.com/14206509/137404958-bfb45dd7-fd91-457e-966f-c7587c018d72.png)


Det är lite samma ide som North Rhine-Westphalian Bibliography  se [How We Built a Spatial Subject Classification Based on Wikidata](https://journal.code4lib.org/articles/15875)
