### ISSUE TITLE
FYI vad Wikidata testat med LIBRISXL ämnesord och vad vi borde göra 

### ISSUE THREAD

**Issue by salgo60** [libris/librisxl#1016]
Här har ni > 1100 LIBRISXL ämnesord kopplade till Wiklidata [på en karta](https://w.wiki/iVh) / som [en lista ](https://w.wiki/4DdW)

![image](https://user-images.githubusercontent.com/14206509/137404958-bfb45dd7-fd91-457e-966f-c7587c018d72.png)

Det är lite samma ide som North Rhine-Westphalian Bibliography  se [How We Built a Spatial Subject Classification Based on Wikidata](https://journal.code4lib.org/articles/15875)

* [video](https://media.ccc.de/v/wikidatacon2019-8-libraries_panel#t=1830
) Using Wikidata to improve spatial subject indexing in a regional bibliography
Adrian Pohl

![image](https://user-images.githubusercontent.com/14206509/137405987-8951a716-2ad0-462e-a923-2584a280080e.png)

* I WIkidata har vi mycket mer som ni skulle kunna skapa egenskaper av och kunna jobba med exempelvis Hembygdsföreningar och klassificera bäcker bättre

  * se tankar https://github.com/salgo60/WikidataBygdeband/issues/13 "Usercase LIBRIS att en Hembygdsförening enkelt kan hitta vilka böcker som beskriver saker i deras närmiljö.... #13"

![image](https://user-images.githubusercontent.com/14206509/137538527-044650d3-dd78-4eaa-9bd3-f55fbd83163e.png)

Se Wikidata Skansen [karta](https://w.wiki/7GB) / [lista](https://w.wiki/4DwP)

![image](https://user-images.githubusercontent.com/14206509/137539154-d7a8b2fc-6b99-4461-8ca3-50116819c242.png)

**Comment by niklasl** [comment]
Det är väldigt kul att använda data som länkats samman. Det är dock märkligt att wikidata-objekten är kopplade till katalogiseringssidor i det administrativa verktyget för katalogisatörer (t.ex. https://libris.kb.se/katalogisering/jgvz4ww25jk9glt) och inte till de formella resurs-URI:erna (här https://libris.kb.se/jgvz4ww25jk9glt#it). Något som borde korrigeras i wikidata.

Observera också att detta är en issue tracker för vår öppna källkod till systemet, inte till den driftsatta applikationen. Här ska bara ärenden som har med koden att göra hanteras (och i regel på engelska, eftersom vi har en internationell målgrupp för denna kod). Det är inget generellt forum, så även om vi tackar för dessa tips och exempel behöver vi flytta sådant till andra kanaler. (Då vi har ett verksamhetsnära arbete har vi inte mycket tid för sådant tyvärr. Vi genomför detta arbete med öppen källkod och länkade data, bland annat för denna typ av mycket positiva bieffekter, men vi kan inte lägga all tid på det.)

**Comment by dpriskorn** [comment]
> 
> 
> Det är väldigt kul att använda data som länkats samman. Det är dock märkligt att wikidata-objekten är kopplade till katalogiseringssidor i det administrativa verktyget för katalogisatörer (t.ex. https://libris.kb.se/katalogisering/jgvz4ww25jk9glt) och inte till de formella resurs-URI:erna (här https://libris.kb.se/jgvz4ww25jk9glt#it). Något som borde korrigeras i wikidata.

Thanks for the tip, fixed https://www.wikidata.org/w/index.php?title=Property%3AP5587&type=revision&diff=1512579591&oldid=1512326555
> 
> Observera också att detta är en issue tracker för vår öppna källkod till systemet, inte till den driftsatta applikationen. Här ska bara ärenden som har med koden att göra hanteras (och i regel på engelska, eftersom vi har en internationell målgrupp för denna kod). Det är inget generellt forum, så även om vi tackar för dessa tips och exempel behöver vi flytta sådant till andra kanaler. (Då vi har ett verksamhetsnära arbete har vi inte mycket tid för sådant tyvärr. Vi genomför detta arbete med öppen källkod och länkade data, bland annat för denna typ av mycket positiva bieffekter, men vi kan inte lägga all tid på det.)

Så var kan vi kommunicera öppet med de driftansvariga? Har KB ett forum likt https://community.dataportal.se/ någonstans? Om inte, vem kan vi önska oss ett sådant av?

En github-yta för det driftsatta libris skulle också funka för min del, där kan både diskussioner och specifika issues tas upp.
