### ISSUE TITLE
Kvalitetskontroll? Finns wikifunktionalitet?

### ISSUE THREAD

**Issue by dpriskorn** [libris/librisxl#1019]
Hej. Jag undrar hur ni tänkt ang. kvalitetskontroll i LibrisXL?

Jag förstår på Martin från YT att det är tänkt att många aktörer som är geografiskt skilda ska samspela om att katalogisera i LibrisXL med länkad data. Är det korrekt?

I det fall så undrar jag om det finns en publik eller ej publik ändringshistorik där man enkelt kan se vem som gjorde vad och när? (typ som en wiki)

Om inte hur ska ni då kunna säkerställa att ni kan hålla god kvalitet?

Se tex https://libris.kb.se/tr574vdc33gk2cc/data.jsonld där ni med textsträngar på titlar refererar till objekt som finns i LibrisXL med unik identifierare. Det håller inte måttet alls om ni frågar mig.

**Comment by salgo60** [comment]
Håller med LIBRISXL verkar ha spårat ur...

[David Shorthouse](https://twitter.com/dpsSpiders) gjorde en [presentation](https://stanford.zoom.us/rec/play/zCW7Zel4sQVeSIgwYL1fAz2E9dytx0_VDdCdKHd2e-CpXQJvS37W-PtohlON9wYLJ3PV_CCH1PR2Kg_s._N9DzHE1blpFqQNL) / [slides](https://www.slideshare.net/DavidShorthouse/ld4-wikidata-affinity-group-shorthouse) vad en auktoritet som KB måste ha för att fungera... mycket finns men vissa saker saknas som versionshistoriken och kunna se ändringar i ert UI 

![image](https://user-images.githubusercontent.com/14206509/137876196-b5a86ffc-85cc-4909-98ca-87d3dac7f8b7.png)

känns som det finns massa textsträngar i KBs data.... borde finnas en knapp/API att markera att detta data har kvalitetsbrister, borde finnas ML som flaggar saker som dåliga, annan "galenskap" är att ni **inte** anger språkkoder på ert data för exempelvis personnamn på [August Strindberg](https://libris.kb.se/tr574vdc33gk2cc/data.jsonld), borde till viss del kunna sättas med Wikidata.... **viktigast är dock att se att ni jobbar med datat**
  
* 2021 snart 10 år in i projektet är den tekniska skulden tråkigt stor....    

Just [August Strindberg](https://libris.kb.se/tr574vdc33gk2cc/data.jsonld) och  "**see also**" Wikipedia [tog jag upp 9 Aug 2019 men](https://web.archive.org/web/20210122031033/https://kundo.se/org/librisxl/d/semantisk-koppling-i-librisxl/) ingenting har hänt... var inte ens säker att frågan förstods

![image](https://user-images.githubusercontent.com/14206509/137883372-64a58905-8589-4db5-9957-951fb2de1145.png)

Det David Shorthouse pekar på i sin [slide 26](https://www.slideshare.net/DavidShorthouse/ld4-wikidata-affinity-group-shorthouse) är att gamla auktoriteter som inte levererar bra digitalt blir ointressanta. 

![image](https://user-images.githubusercontent.com/14206509/137880625-659909fc-8a52-4dd5-9b8c-dcae7aad4c51.png)

**Tycker mig inte se en ljusning i LIBRISXL tunneln** och [fler med mig](https://universitetslararen.se/2019/03/21/kb-langt-ifran-klart-med-uppdraget-att-digitalisera/)....  

![image](https://user-images.githubusercontent.com/14206509/137884212-f9f24de1-0bac-4920-8770-c024bb455551.png)
