### ISSUE TITLE
Encoding problems in index

### ISSUE THREAD

**Issue by mskold** [libris/librisxl#107]
åäö is encoded differently in localhost compared to cluster. see attached notes

**Comment by mskold** [comment]
On localhost:
{
    "_shards": {
        "failed": 0,
        "successful": 5,
        "total": 5
    },
    "aggregations": {
        "titles": {
            "buckets": [
                {
                    "doc_count": 1,
                    "key": "anteckning"
                },
                {
                    "doc_count": 1,
                    "key": "en"
                },
                {
                    "doc_count": 1,
                    "key": "fr\u00e5"
                },
                {
                    "doc_count": 1,
                    "key": "\u00f6"
                }
            ],
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0
        }
    },
    "hits": {
        "hits": [
            {
                "_id": "L2JpYi83MTQ5NTkz",
                "_index": "libris_index-20150323.113912",
                "_score": 4.433987,
                "_source": {
                    "@id": "/bib/7149593",
                    "@type": "Record",
                    "about": {
                        "@id": "/resource/bib/7149593",
                        "@type": [
                            "Text",
                            "Monograph"
                        ],
                        "attributedTo": {
                            "@id": "/resource/auth/191503",
                            "@type": "Person",
                            "birthYear": "1914",
                            "deathYear": "2001",
                            "familyName": "Jansson",
                            "givenName": "Tove"
                        },
                        "biography": {
                            "@id": "/def/enum/content/Autobiography"
                        },
                        "classification": [
                            {
                                "@id": "http://dewey.info/class/839.7374/e23/",
                                "@type": "Concept",
                                "inScheme": {
                                    "@id": "http://dewey.info/scheme/edition/e23/swe/",
                                    "@type": "ConceptScheme",
                                    "isVersionOf": {
                                        "@id": "http://dewey.info/scheme/ddc/"
                                    },
                                    "language": "swe",
                                    "notation": "DDC",
                                    "version": "23"
                                },
                                "notation": "839.7374"
                            },
                            {
                                "@id": "/topic/kssb/6/Gcdz%20Jansson%2C%20Tove",
                                "@type": "Concept",
                                "inScheme": {
                                    "@id": "/topic/kssb/6",
                                    "@type": "ConceptScheme",
                                    "notation": "kssb/6"
                                },
                                "notation": "Gcdz Jansson, Tove"
                            },
                            {
                                "@id": "/topic/kssb/6/Ibz%20Pietil%C3%A4%2C%20Tuulikki",
                                "@type": "Concept",
                                "inScheme": {
                                    "@id": "/topic/kssb/6",
                                    "@type": "ConceptScheme",
                                    "notation": "kssb/6"
                                },
                                "notation": "Ibz Pietil\u00e4, Tuulikki"
                            },
                            {
                                "@id": "/topic/kssb/Lz",
                                "@type": "Concept",
                                "notation": "Lz"
                            },
                            {
                                "@id": "/topic/sab/Gcdz",
                                "@type": "Concept",
                                "inScheme": {
                                    "@id": "/topic/sab",
                                    "@type": "ConceptScheme",
                                    "notation": "sab"
                                },
                                "notation": "Gcdz",
                                "prefLabel": "Litteraturhistoria Finlandssvensk"
                            },
                            {
                                "@id": "/topic/sab/Ibz",
                                "@type": "Concept",
                                "inScheme": {
                                    "@id": "/topic/sab",
                                    "@type": "ConceptScheme",
                                    "notation": "sab"
                                },
                                "notation": "Ibz",
                                "prefLabel": "Konst Konsthistoria"
                            }
                        ],
                        "comment": [
                            "\u00c4ven tillg. med tryck\u00e5r: 2. uppl., 1996"
                        ],
                        "confPub": {
                            "@id": "/def/enum/content/NotAConferencePublication"
                        },
                        "creator": [
                            {
                                "@id": "/resource/auth/191503",
                                "@type": "Person",
                                "birthYear": "1914",
                                "deathYear": "2001",
                                "familyName": "Jansson",
                                "givenName": "Tove"
                            },
                            {
                                "@type": "Person",
                                "birthYear": "1917",
                                "deathYear": "2009",
                                "familyName": "Pietil\u00e4",
                                "givenName": "Tuulikki"
                            }
                        ],
                        "festschrift": {
                            "@id": "/def/enum/content/NotAFestschrift"
                        },
                        "hasFormat": [
                            {
                                "@type": "Product",
                                "dimensions": "25 cm",
                                "extent": "102, [1] s.",
                                "otherPhysicalDetails": "ill."
                            }
                        ],
                        "identifier": [
                            {
                                "@type": "Identifier",
                                "identifierNote": "inb.",
                                "identifierScheme": {
                                    "@id": "/def/identifiers/isbn"
                                },
                                "identifierValue": "91-0-056322-6"
                            }
                        ],
                        "index": {
                            "@id": "/def/enum/content/NoIndex"
                        },
                        "influencedBy": [
                            {
                                "@type": "Person",
                                "birthYear": "1917",
                                "deathYear": "2009",
                                "familyName": "Pietil\u00e4",
                                "givenName": "Tuulikki"
                            }
                        ],
                        "instanceTitle": {
                            "@type": "Title",
                            "titleValue": "Anteckningar fr\u00e5n en \u00f6"
                        },
                        "isbn": [
                            "9100563226"
                        ],
                        "language": [
                            {
                                "@id": "/def/languages/swe"
                            }
                        ],
                        "literaryForm": {
                            "@id": "/def/enum/content/NotFictionNotFurtherSpecified"
                        },
                        "manufacture": [
                            {
                                "@type": "ProviderEvent",
                                "place": {
                                    "@type": "Place",
                                    "label": "Finland"
                                }
                            }
                        ],
                        "publication": [
                            {
                                "@type": "ProviderEvent",
                                "place": {
                                    "@type": "Place",
                                    "label": "Stockholm"
                                },
                                "providerDate": "1996",
                                "providerName": "Bonnier"
                            }
                        ],
                        "publicationCountry": [
                            {
                                "@id": "/def/countries/sw"
                            }
                        ],
                        "responsibilityStatement": "Tove Jansson, Tuulikki Pietil\u00e4",
                        "subject": [
                            {
                                "@id": "/resource/auth/191503",
                                "@type": "Person",
                                "birthYear": "1914",
                                "deathYear": "2001",
                                "familyName": "Jansson",
                                "givenName": "Tove"
                            },
                            {
                                "@type": "Person",
                                "birthYear": "1917",
                                "deathYear": "2009",
                                "familyName": "Pietil\u00e4",
                                "givenName": "Tuulikki"
                            }
                        ],
                        "termsOfAvailability": "310:00",
                        "title": "Anteckningar fr\u00e5n en \u00f6"
                    },
                    "bibliography": [
                        {
                            "@type": "Organization",
                            "notation": "BULB"
                        },
                        {
                            "@type": "Organization",
                            "notation": "NB"
                        },
                        {
                            "@type": "Organization",
                            "notation": "SEE"
                        },
                        {
                            "@type": "Organization",
                            "notation": "SLB"
                        },
                        {
                            "@type": "Organization",
                            "notation": "KVIN"
                        }
                    ],
                    "catForm": {
                        "@id": "/def/enum/record/AACR2"
                    },
                    "controlNumber": "7149593",
                    "created": "2015-03-23T11:39:50.640000000+01:00",
                    "encodedId": "L2JpYi83MTQ5NTkz",
                    "librisIIINumber": [
                        "9100563226"
                    ],
                    "modified": "2014-06-10T10:05:06.0+02:00",
                    "originalCatalogingAgency": {
                        "@type": "Organization",
                        "name": "NB"
                    }
                },
                "_type": "bib"
            }
        ],
        "max_score": 4.433987,
        "total": 1
    },
    "timed_out": false,
    "took": 23
}

**Comment by mskold** [comment]
On cluster:
{
    "_shards": {
        "failed": 0,
        "successful": 9,
        "total": 9
    },
    "aggregations": {
        "titles": {
            "buckets": [
                {
                    "doc_count": 1,
                    "key": "anteckningar"
                },
                {
                    "doc_count": 1,
                    "key": "en"
                },
                {
                    "doc_count": 1,
                    "key": "fra\u030an"
                },
                {
                    "doc_count": 1,
                    "key": "o\u0308"
                }
            ],
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0
        }
    },
    "hits": {
        "hits": [
            {
                "_id": "L2JpYi83MTQ5NTkz",
                "_index": "libris_index-20150318.173457",
                "_score": 15.447702,
                "_source": {
                    "@id": "/bib/7149593",
                    "@type": "Record",
                    "about": {
                        "@id": "/resource/bib/7149593",
                        "@type": [
                            "Text",
                            "Monograph"
                        ],
                        "attributedTo": {
                            "@id": "/resource/auth/191503",
                            "@type": "Person",
                            "birthYear": "1914",
                            "deathYear": "2001",
                            "familyName": "Jansson",
                            "givenName": "Tove"
                        },
                        "biography": {
                            "@id": "/def/enum/content/Autobiography",
                            "@type": "Concept",
                            "inCollection": [
                                {
                                    "@id": "/def/enum/content/biography-collection"
                                },
                                {
                                    "@id": "/def/enum/content/text-collection"
                                }
                            ],
                            "prefLabel": "Sj\u00e4lvbiografisk text",
                            "prefLabel_en": "Autobiography",
                            "related": [
                                {
                                    "@id": "/def/terms#Text"
                                },
                                {
                                    "@id": "/def/terms#Audio"
                                }
                            ]
                        },
                        "classification": [
                            {
                                "@id": "http://dewey.info/class/839.7374/e23/",
                                "@type": "Concept",
                                "inScheme": {
                                    "@id": "http://dewey.info/scheme/edition/e23/swe/",
                                    "@type": "ConceptScheme",
                                    "isVersionOf": {
                                        "@id": "http://dewey.info/scheme/ddc/"
                                    },
                                    "language": "swe",
                                    "notation": "DDC",
                                    "version": "23"
                                },
                                "notation": "839.7374"
                            },
                            {
                                "@id": "/topic/kssb/6/Gcdz%20Jansson%2C%20Tove",
                                "@type": "Concept",
                                "inScheme": {
                                    "@id": "/topic/kssb/6",
                                    "@type": "ConceptScheme",
                                    "notation": "kssb/6"
                                },
                                "notation": "Gcdz Jansson, Tove"
                            },
                            {
                                "@id": "/topic/kssb/6/Ibz%20Pietila%CC%88%2C%20Tuulikki",
                                "@type": "Concept",
                                "inScheme": {
                                    "@id": "/topic/kssb/6",
                                    "@type": "ConceptScheme",
                                    "notation": "kssb/6"
                                },
                                "notation": "Ibz Pietila\u0308, Tuulikki"
                            },
                            {
                                "@id": "/topic/kssb/Lz",
                                "@type": "Concept",
                                "notation": "Lz"
                            },
                            {
                                "@id": "/topic/sab/Gcdz",
                                "@type": "Concept",
                                "inScheme": {
                                    "@id": "/topic/sab",
                                    "@type": "ConceptScheme",
                                    "notation": "sab"
                                },
                                "notation": "Gcdz",
                                "prefLabel": "Litteraturhistoria Finlandssvensk"
                            },
                            {
                                "@id": "/topic/sab/Ibz",
                                "@type": "Concept",
                                "inScheme": {
                                    "@id": "/topic/sab",
                                    "@type": "ConceptScheme",
                                    "notation": "sab"
                                },
                                "notation": "Ibz",
                                "prefLabel": "Konst Konsthistoria"
                            }
                        ],
                        "comment": [
                            "A\u0308ven tillg. med trycka\u030ar: 2. uppl., 1996"
                        ],
                        "confPub": {
                            "@id": "/def/enum/content/NotAConferencePublication",
                            "@type": "Concept",
                            "inCollection": [
                                {
                                    "@id": "/def/enum/content/confPub-collection"
                                }
                            ],
                            "prefLabel": "Nej, resursen h\u00e4rr\u00f6r ej fr\u00e5n konferens",
                            "prefLabel_en": "Not a conference publication",
                            "related": [
                                {
                                    "@id": "/def/terms#Text"
                                },
                                {
                                    "@id": "/def/terms#Serial"
                                }
                            ]
                        },
                        "creator": [
                            {
                                "@id": "/resource/auth/191503",
                                "@type": "Person",
                                "birthYear": "1914",
                                "deathYear": "2001",
                                "familyName": "Jansson",
                                "givenName": "Tove"
                            },
                            {
                                "@type": "Person",
                                "birthYear": "1917",
                                "deathYear": "2009",
                                "familyName": "Pietila\u0308",
                                "givenName": "Tuulikki"
                            }
                        ],
                        "festschrift": {
                            "@id": "/def/enum/content/NotAFestschrift",
                            "@type": "Concept",
                            "inCollection": [
                                {
                                    "@id": "/def/enum/content/festschrift-collection"
                                }
                            ],
                            "prefLabel": "Nej, resursen \u00e4r inte festskrift",
                            "prefLabel_en": "Not a festschrift",
                            "related": [
                                {
                                    "@id": "/def/terms#Text"
                                }
                            ]
                        },
                        "hasFormat": [
                            {
                                "@type": "Product",
                                "dimensions": "25 cm",
                                "extent": "102, [1] s.",
                                "otherPhysicalDetails": "ill."
                            }
                        ],
                        "identifier": [
                            {
                                "@type": "Identifier",
                                "identifierNote": "inb.",
                                "identifierScheme": {
                                    "@id": "/def/identifiers/isbn"
                                },
                                "identifierValue": "91-0-056322-6"
                            }
                        ],
                        "index": {
                            "@id": "/def/enum/content/NoIndex"
                        },
                        "influencedBy": [
                            {
                                "@type": "Person",
                                "birthYear": "1917",
                                "deathYear": "2009",
                                "familyName": "Pietila\u0308",
                                "givenName": "Tuulikki"
                            }
                        ],
                        "instanceTitle": {
                            "@type": "Title",
                            "titleValue": "Anteckningar fra\u030an en o\u0308"
                        },
                        "isbn": [
                            "9100563226"
                        ],
                        "language": [
                            {
                                "@id": "/def/languages/swe",
                                "@type": [
                                    "Language",
                                    "Concept"
                                ],
                                "langCode": "swe",
                                "langTag": "sv",
                                "matches": "http://id.loc.gov/vocabulary/iso639-2/swe",
                                "notation": "swe",
                                "prefLabel": "Svenska",
                                "prefLabel_en": "Swedish"
                            }
                        ],
                        "literaryForm": {
                            "@id": "/def/enum/content/NotFictionNotFurtherSpecified",
                            "@type": "Concept",
                            "inCollection": [
                                {
                                    "@id": "/def/enum/content/literaryForm-collection"
                                }
                            ],
                            "prefLabel": "Ej sk\u00f6nlitter\u00e4rt verk",
                            "prefLabel_en": "Not fiction (not further specified)",
                            "related": [
                                {
                                    "@id": "/def/terms#Text"
                                }
                            ]
                        },
                        "manufacture": [
                            {
                                "@type": "ProviderEvent",
                                "place": {
                                    "@type": "Place",
                                    "label": "Finland"
                                }
                            }
                        ],
                        "publication": [
                            {
                                "@type": "ProviderEvent",
                                "place": {
                                    "@type": "Place",
                                    "label": "Stockholm"
                                },
                                "providerDate": "1996",
                                "providerName": "Bonnier"
                            }
                        ],
                        "publicationCountry": [
                            {
                                "@id": "/def/countries/sw",
                                "@type": [
                                    "Concept",
                                    "Country"
                                ],
                                "exactMatch": "http://id.loc.gov/vocabulary/countries/sw",
                                "label_en": "Sweden",
                                "notation": "sw",
                                "prefLabel": "Sverige",
                                "prefLabel_en": "Sweden"
                            }
                        ],
                        "responsibilityStatement": "Tove Jansson, Tuulikki Pietila\u0308",
                        "subject": [
                            {
                                "@id": "/resource/auth/191503",
                                "@type": "Person",
                                "birthYear": "1914",
                                "deathYear": "2001",
                                "familyName": "Jansson",
                                "givenName": "Tove"
                            },
                            {
                                "@type": "Person",
                                "birthYear": "1917",
                                "deathYear": "2009",
                                "familyName": "Pietila\u0308",
                                "givenName": "Tuulikki"
                            }
                        ],
                        "termsOfAvailability": "310:00",
                        "title": "Anteckningar fra\u030an en o\u0308"
                    },
                    "bibliography": [
                        {
                            "@type": "Organization",
                            "notation": "BULB"
                        },
                        {
                            "@type": "Organization",
                            "notation": "NB"
                        },
                        {
                            "@type": "Organization",
                            "notation": "SEE"
                        },
                        {
                            "@type": "Organization",
                            "notation": "SLB"
                        },
                        {
                            "@type": "Organization",
                            "notation": "KVIN"
                        }
                    ],
                    "catForm": {
                        "@id": "/def/enum/record/AACR2"
                    },
                    "controlNumber": "7149593",
                    "created": "1996-02-14T00:00:00.0+01:00",
                    "encodedId": "L2JpYi83MTQ5NTkz",
                    "librisIIINumber": [
                        "9100563226"
                    ],
                    "modified": "2014-06-10T12:05:05.0+02:00",
                    "originalCatalogingAgency": {
                        "@type": "Organization",
                        "name": "NB"
                    }
                },
                "_type": "bib"
            }
        ],
        "max_score": 15.447702,
        "total": 1
    },
    "timed_out": false,
    "took": 3219
}

**Comment by niklasl** [comment]
Looks like these are stored in decomposed form on the cluster (see e.g. [ES doc on unicode normalization]( http://www.elastic.co/guide/en/elasticsearch/guide/current/unicode-normalization.html)).

Also, looks like stemmed data on localhost (with a weird change from "från" to "frå"...).

**Comment by niklasl** [comment]
A possible cause of this difference is the different way data has been transported (and thus serialized/deserialized) to the load process (via OAI-PHM versus directly from database).

**Comment by mskold** [comment]
Solved by normalizing string from mysql
