### ISSUE TITLE
Inconsistent values for about.numberOfItems

### ISSUE THREAD

**Issue by mskold** [libris/librisxl#117]
In some cases about.numberOfItems are numeric, but sometimes the values are strings. This leads to MapperParsingExceptions in elasticsearch. 
Case in point: 'NumberFormatException: For input string: "1  "'

Two possible solutions:
1) make sure all numberOfItems are numeric in marcconversion
2) explicitly map about.numberOfItems to strings in elasticsearch (makes comparison searches against the field impossible)

**Comment by niklasl** [comment]
Solution 1 is only possible if we delete (possibly broken) non-numeric values. From this given case (value `"1 "`), we should probably trim the string before parsing, although it *looks* strange to get that value in a controlled fixed field. Which holding contained that value? 

If we don't want to drop broken `numberOfItems`, we could extend the conversion to use a parallell `numberOfItemsText` for these values (`numberOfItems` can be bound to `@type`: `xsd:integer` in the JSON-LD context, and `numberOfItemsText` can be an unbound version mapped to the same vocabulary term).

**Comment by niklasl** [comment]
Or, we could remove the attempt to create real numbers at all (keep them all as strings) in the conversion.

**Comment by mskold** [comment]
(One of) the offending records
{
    "@id": "/hold/34257066",
    "@type": "Record",
    "_marcUncompleted": [
        {
            "035": {
                "ind1": " ",
                "ind2": " ",
                "subfields": [
                    {
                        "a": "(Sko)16847"
                    }
                ]
            }
        },
        {
            "599": {
                "ind1": " ",
                "ind2": " ",
                "subfields": [
                    {
                        "a": "EW79/AO09"
                    }
                ]
            }
        },
        {
            "653": {
                "ind1": " ",
                "ind2": " ",
                "subfields": [
                    {
                        "a": "1700"
                    }
                ]
            }
        }
    ],
    "about": {
        "@id": "/resource/hold/34257066",
        "@type": "HeldMaterial",
        "expectedAcquisitionEndDate": "0   ",
        "heldBy": {
            "@type": "Organization",
            "notation": "Sko"
        },
        "holdingFor": {
            "@id": "/resource/bib/13582642",
            "@reverse": {
                "about": {
                    "controlNumber": "13582642"
                }
            },
            "@type": [
                "Text",
                "Monograph"
            ]
        },
        "immediateSourceOfAcquisitionOfItem": [
            {
                "ind1": " ",
                "ind2": " ",
                "subfields": [
                    {
                        "a": "Kostar inbunden --- Dr 7 kmtt Stockh. d. 26 9ber 1745 CG Bielke (fp. ins. bl\u00e4ck)."
                    }
                ]
            }
        ],
        "lendingPolicy": {
            "@id": "/def/enum/content/WillNotLend"
        },
        "numberOfItems": "1  ",
        "offers": [
            {
                "@type": "Offer",
                "availability": [
                    "Utl\u00e5nas ej"
                ],
                "copyNote": [
                    "Guldtryckt titel (huvud). Anteckningat i marginalen och understrykningar."
                ],
                "heldBy": [
                    {
                        "@type": "Organization",
                        "notation": "Sko"
                    }
                ]
            }
        ],
        "workExample": [
            {
                "@type": "Product",
                "custodialHistoryOfItem": [
                    "Inklistrat graverat exlibris: Grevliga Bielkevapnet av Jean Eric (fp. ins.)."
                ]
            },
            {
                "@type": "Product",
                "custodialHistoryOfItem": [
                    "Handskrivet register (volymens sitsa 8 blad, bl\u00e4ck)."
                ]
            },
            {
                "@type": "Product",
                "bindingInformation": [
                    "P\u00e4rmar av marmorerat papper, rygg ochh\u00f6rn av pergament. R\u00f6dst\u00e4nkt snitt."
                ]
            }
        ]
    },
    "controlNumber": "34257066",
    "created": "2012-11-02T00:00:00.0+01:00",
    "date": "0     ",
    "encLevel": {
        "@id": "/def/enum/record/HoldingsLevel1"
    },
    "holdingType": {
        "@id": "/def/enum/record/SinglePartItemHolding"
    },
    "modified": "2012-11-07T11:04:35.0+01:00",
    "statistics": {
        "@id": "/def/enum/record/Retrospektiv_katalogisering"
    }
}
