### ISSUE TITLE
REST DELETE for bib records returns java.lang.NullPointerException: Cannot get property 'notation' on null object

### ISSUE THREAD

**Issue by sweco-semhul** [libris/librisxl#126]
When checking permissions for delete record param newdoc is set to null:
https://github.com/libris/librisxl/blob/develop/rest/src/main/groovy/whelk/rest/api/Crud.groovy#L469

This results in security check being done as if the record where a holding causing a nullpointer when trying to get heldBy.notation:
https://github.com/libris/librisxl/blob/develop/rest/src/main/groovy/whelk/rest/security/AccessControl.groovy#L27

**Comment by sweco-semhul** [comment]
@mskold unclear if this kind of issue should be reported in Github or Jira, but this was the easiest option.

**Comment by mskold** [comment]
Fixed in 33c84a8cdeac0864f1fb12ccfadefbffa44a6b6a
