### ISSUE TITLE
ListSets in oaipmh renders bad XML

### ISSUE THREAD

**Issue by mskold** [libris/librisxl#138]
When accessing /oaipmh?verb=ListSets the server responds with:

This page contains the following errors:

error on line 1 at column 101476: Extra content at the end of the document

**Comment by fontanka16** [comment]
Fixed issue in 2540196399c5f2607086efd3bce9e5364c24cc87, but could not reproduce the above mentioned error. Instead i got strange time outs when querying the production server. Debugging in Jetty showed working code, but when debugging in Tomcat i suddenly got another error. That one is now taken care of and production code seem to run smoothly.
