### ISSUE TITLE
OAIPMH set to load all bibs for a sigel

### ISSUE THREAD

**Issue by mskold** [libris/librisxl#141]
The OAIPMH service should be able to load all "bib"-records for a given Sigel. The old OAIPMH has this functionality and the new must also.

**Comment by niklasl** [comment]
As in instances for which there are items held by the given library? Or as in "catalogued by"?

**Comment by mskold** [comment]
Where items are held by the given library.

**Comment by niklasl** [comment]
This might be accomplished by building on our general search mechanism (even the part that doesn't need ES).

We either need to join across relations at runtime (or a graph index), or maintain this in the (ES) index (and use like: `find?@reverse.itemOf.heldBy.@id=/library/S`).

Or this needs to be built as a service (unless clients can do it on their own):

        for item in find?heldBy.@id=/library/S:
            yield itemOf.@id

We need to elaborate on how and by whom this feature is to be used, to establish acceptance tests.
